spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:test;MODE=ORACLE;DB_CLOSE_DELAY=-1"
    username: sa
    password:
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521/xe
#    username: ERP
#    password: java
server:
  port: 8080
